name: MathJax Tests

on:
  push:
    branches:
      - dev
      - production
  pull_request:
    branches:
      - dev
      - production

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test